// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrderSystemAPI.Data;

namespace OrderSystemAPI.Data.Migrations
{
    [DbContext(typeof(OrderContext))]
    partial class OrderContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OrderSystemAPI.Models.FullOrder", b =>
                {
                    b.Property<Guid>("OrderID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("orderEntryCustomerID");

                    b.HasKey("OrderID");

                    b.HasIndex("orderEntryCustomerID");

                    b.ToTable("FullOrders");
                });

            modelBuilder.Entity("OrderSystemAPI.Models.Item", b =>
                {
                    b.Property<string>("ProductID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("OrderEntryCustomerID");

                    b.Property<int>("Quantity");

                    b.HasKey("ProductID");

                    b.HasIndex("OrderEntryCustomerID");

                    b.ToTable("Item");
                });

            modelBuilder.Entity("OrderSystemAPI.Models.OrderEntry", b =>
                {
                    b.Property<string>("CustomerID")
                        .ValueGeneratedOnAdd();

                    b.HasKey("CustomerID");

                    b.ToTable("OrderEntries");
                });

            modelBuilder.Entity("OrderSystemAPI.Models.Products", b =>
                {
                    b.Property<string>("ProductID")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("FullOrderOrderID");

                    b.Property<string>("ProductName");

                    b.Property<double>("ProductPrice");

                    b.HasKey("ProductID");

                    b.HasIndex("FullOrderOrderID");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("OrderSystemAPI.Models.FullOrder", b =>
                {
                    b.HasOne("OrderSystemAPI.Models.OrderEntry", "orderEntry")
                        .WithMany()
                        .HasForeignKey("orderEntryCustomerID");
                });

            modelBuilder.Entity("OrderSystemAPI.Models.Item", b =>
                {
                    b.HasOne("OrderSystemAPI.Models.OrderEntry")
                        .WithMany("Items")
                        .HasForeignKey("OrderEntryCustomerID");
                });

            modelBuilder.Entity("OrderSystemAPI.Models.Products", b =>
                {
                    b.HasOne("OrderSystemAPI.Models.FullOrder")
                        .WithMany("Products")
                        .HasForeignKey("FullOrderOrderID");
                });
#pragma warning restore 612, 618
        }
    }
}
